### PR TITLE
Bdsky plot

### PR DESCRIPTION
**Pull request by carlopacioni**
Implemented Denise Kuehnert's code to plot BDSKY as R package function and modified it to allow parameter names to be passed with arguments and to handle parameter with multiple dimension.

Cheers

### CODE REVIEW

**Comment by richelbilderbeek** [comment]
Sorry for responding so slowly! I thought I was just a collaborator of this GitHub, instead of just a contributor. I will accept if Travis CI is fine with it :sunglasses:

**Comment by richelbilderbeek** [comment]
This is appears to go wrong thanks to dependency on `Hmisc`. Thanks to this, I cannot see how `lintr` and `goodpractice` judge the code its quality. I will accept this Pull Request if you volunteer to fix the possible flaws indicated by `lintr` and `goodpractice`. This package will look stupid if the Build status would be broken for a long time on the `master` branch.

**Comment by richelbilderbeek** [comment]
Ah, there is that pesky `Hmisc`: it is your new proposed `DESCRIPTION`. Please remove it, push again and let's see what Travis has to say. Good luck :+1:

**Comment by carlopacioni** [comment]
Sorry for the late reply, just made it back from 2 week leave. I'll have a
look at this during th8s coming week as soon as I get a chance.

Thanks,
Carlo

**Comment by carlopacioni** [comment]
Hello, this seems to be a travis problem. Following suggested fix from https://github.com/travis-ci/travis-ci/issues/6850#issuecomment-266548181 has resolved the issue and I get a green light now. Let me know if you see any other issue.

Thanks! carlo

**Comment by richelbilderbeek** [comment]
Thanks, well done!

**Comment by carlopacioni** [comment]
Hello, this seems to be a travis problem. Following the suggested fix from https://github.com/travis-ci/travis-ci/issues/6850#issuecomment-266548181 has resolved the issue and I get a green light now. Let me know if you see any other issue.

Thanks! carlo

**Pull request merged**
